version: '3.8'
services:
  web:
    image: pedrobarbosa996/monitora:monitora-nodeweb
    container_name: monitora-web
    ports:
      - "3333:3333"
    environment:
      - APP_PORT=3333
      - APP_HOST=0.0.0.0
      - DB_HOST=$IP_BD
      - DB_USER=monitora
      - DB_PASSWORD=monitora@1234
      - DB_DATABASE=monitora
    restart: unless-stopped
