services:
  monitora-db:
    image: pedrobarbosa996/monitora:monitora-mysql
    container_name: monitora-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: monitora
      MYSQL_USER: adminmonitora
      MYSQL_PASSWORD: senha123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monitora-network

volumes:
  mysql_data:

networks:
  monitora-network:
    driver: bridge